name: pytorch_env
channels:
  - ngam
  - conda-forge
dependencies:
  - aom=3.4.0
  - appdirs=1.4.4
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - atk-1.0=2.36.0
  - attrs=22.1.0
  - audioread=2.1.9
  - autopep8=1.6.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bleach=5.0.1
  - blosc=1.21.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-blosc2=2.2.0
  - ca-certificates=2022.6.15
  - cairo=1.16.0
  - certifi=2022.6.15
  - cffi=1.15.1
  - cfitsio=4.1.0
  - charls=2.3.4
  - charset-normalizer=2.1.0
  - cloudpickle=2.1.0
  - colorama=0.4.5
  - cryptography=37.0.4
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2022.8.0
  - dav1d=1.0.0
  - debugpy=1.6.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - et_xmlfile=1.0.1
  - executing=0.9.1
  - expat=2.4.8
  - ffmpeg=4.3.2
  - flit-core=3.7.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.34.4
  - freetype=2.10.4
  - fribidi=1.0.10
  - fsspec=2022.7.1
  - future=0.18.2
  - gdk-pixbuf=2.42.8
  - gettext=0.19.8.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - graphite2=1.3.13
  - graphviz=3.0.0
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=3.4.0
  - hdf5=1.12.1
  - icu=69.1
  - idna=3.3
  - imagecodecs=2022.7.31
  - imageio=2.21.0
  - importlib-metadata=4.11.4
  - importlib_resources=5.9.0
  - ipykernel=6.15.1
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.1
  - jasper=2.0.33
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.0
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.9.1
  - jupyter=1.0.0
  - jupyter_client=7.3.4
  - jupyter_console=6.4.4
  - jupyter_core=4.11.1
  - jupyterlab=2.1.0
  - jupyterlab_server=1.0.9
  - jupyterlab_widgets=1.1.1
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.12
  - lerc=4.0.0
  - libaec=1.0.6
  - libavif=0.10.1
  - libblas=3.9.0
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas=3.9.0
  - libcurl=7.83.1
  - libcxx=14.0.6
  - libdeflate=1.13
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libflac=1.3.4
  - libgd=2.3.3
  - libgfortran=5.0.0.dev0
  - libgfortran5=11.0.1.dev0
  - libglib=2.72.1
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.47.0
  - libogg=1.3.4
  - libopenblas=0.3.20
  - libopencv=4.5.3
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.18.1
  - librosa=0.9.1
  - librsvg=2.52.5
  - libsndfile=1.0.31
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libtool=2.4.6
  - libvorbis=1.3.7
  - libwebp=1.2.3
  - libwebp-base=1.2.3
  - libxcb=1.13
  - libxml2=2.9.12
  - libzlib=1.2.12
  - libzopfli=1.0.3
  - llvm-openmp=14.0.4
  - llvmlite=0.38.1
  - locket=1.0.0
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - munkres=1.1.4
  - nbconvert=5.6.1
  - nbformat=5.4.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.6
  - networkx=2.8.5
  - ninja=1.11.0
  - notebook=6.4.12
  - numba=0.55.1
  - numpy=1.21.6
  - opencv=4.5.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openpyxl=3.0.9
  - openssl=1.1.1q
  - packaging=21.3
  - pandocfilters=1.5.0
  - pango=1.50.5
  - parso=0.8.3
  - partd=1.2.0
  - patsy=0.5.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - plotly=5.8.0
  - pooch=1.6.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.30
  - prompt_toolkit=3.0.30
  - psutil=5.9.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-opencv=4.5.3
  - pycodestyle=2.9.1
  - pycparser=2.21
  - pydub=0.25.1
  - pygments=2.12.0
  - pyopengl=3.1.6
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - pysoundfile=0.10.3.post1
  - python=3.9.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.1
  - python-graphviz=0.20
  - python_abi=3.9
  - pytorch=1.10.0
  - pytorch-model-summary=0.1.1
  - pytz=2022.1
  - pywavelets=1.3.0
  - pyyaml=6.0
  - pyzmq=23.2.0
  - readline=8.1.2
  - requests=2.28.1
  - resampy=0.3.1
  - scikit-image=0.19.3
  - scikit-learn=1.1.1
  - scipy=1.9.0
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - send2trash=1.8.0
  - setuptools=62.3.3
  - six=1.16.0
  - sleef=3.5.1
  - snappy=1.1.9
  - sqlite=3.39.2
  - stack_data=0.3.0
  - statsmodels=0.13.2
  - tenacity=8.0.1
  - terminado=0.15.0
  - testpath=0.6.0
  - threadpoolctl=3.1.0
  - tifffile=2022.8.3
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - torchaudio=0.10.0
  - torchinfo=1.7.0
  - torchvision=0.9.1
  - torchvision-cpu=0.9.1
  - tornado=6.2
  - tqdm=4.64.0
  - traitlets=5.3.0
  - typing_extensions=4.3.0
  - tzdata=2022a
  - unicodedata2=14.0.0
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.6.1
  - x264=1!161.3030
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.8.1
  - zlib=1.2.12
  - zlib-ng=2.0.6
  - zstd=1.5.2
